Feature/user update
k2madureira/ioasysImdb pull request #4
Opened 2021-01-25 18:50 UTC by k2madureira

Update user

2021-01-25 20:22 UTC, christophercmoura approved these changes

2021-01-25 21:09 UTC, diegolssantos commented on src/helpers/messages.js
> +  notFoundFields: (resource) => `${resource} not-found`,
Já que são `fieldS`, não deveria receber um `array` e a mensagem ser adaptada para isso?

2021-01-25 21:16 UTC, k2madureira commented on src/helpers/messages.js
> +  notFoundFields: (resource) => `${resource} not-found`,
Aplicado

2021-01-25 21:22 UTC, diegolssantos commented on src/routes/users.routes.js
> +router.put('/update/:id', validate(users.update), userController.update);
Pelo padrão REST, suas rotas não precisam ter os verbos embutidos, basta que você controle-as pelos verbos:

Por exemplo: essa linha precisa ser apenas: `router.put('/:id', validate(users.update), userController.update);`

2021-01-25 21:26 UTC, diegolssantos commented on src/services/users/create.service.js
> +    if (findAdm.length === 0 && admin === true) {
Não seria interessante criar um outro middleware para validar se o usuário também é um admin?
Já que só alguns serviços são específicos de uso do admin, com um middleware, você não vai precisar replicar essa validação em todos esses endpoints.

2021-01-25 21:29 UTC, diegolssantos commented on src/services/users/create.service.js
>      const findUser = await userRepository.find({ email });
Sugestão (Não precisa alterar se não quiser): crie um método findOne(params) e outro findAll(params), assim você consegue usar um ou outro dependendo do contexto.

2021-01-25 21:32 UTC, diegolssantos commented on src/services/users/session.service.js
> +    if (userData.disabled === true) {
Aqui a ideia é semelhante à do middleware, mas, no caso, você poderia utilizar um `findOne({ where: { email, disabled: false });`, assim você elimina a necessidade dessa validação e fica apenas com a validação anterior.

2021-01-25 21:32 UTC, k2madureira commented on src/services/users/create.service.js
> +    if (findAdm.length === 0 && admin === true) {
entendo, porem esses serviços não são utilizados apenas por adm. Caso a regra alterasse para que apenas adm possam cadastrar é uma ideia totalmente válida

2021-01-25 21:33 UTC, diegolssantos commented on src/services/users/update.service.js
> +    const findAdm = await userRepository.find({
Aqui nesse serviço também valem as mesmas ideias dos comentários anteriores.

2021-01-25 21:34 UTC, k2madureira commented on src/routes/users.routes.js
> +router.put('/update/:id', validate(users.update), userController.update);
ficaria a diferença apenas no tipo do metodo chamado?

2021-01-25 21:36 UTC, diegolssantos commented on src/services/users/create.service.js
> +    if (findAdm.length === 0 && admin === true) {
É só fazer o caminho contrário, você pode criar o middleware e não utilizar ele nos endpoints que você não precisar. Basta adicionar nas rotas dependendo da regra.

2021-01-25 21:40 UTC, k2madureira commented on src/services/users/create.service.js
> +    if (findAdm.length === 0 && admin === true) {
entendo, vou criar

2021-01-26 11:49 UTC, k2madureira commented on src/services/users/create.service.js
>      const findUser = await userRepository.find({ email });
criado

2021-01-26 11:56 UTC, k2madureira commented on src/services/users/session.service.js
> +    if (userData.disabled === true) {
Essa segunda verificação é para identificar se o usuário que esta tentando realizar login foi deletado logicamente

2021-01-26 11:58 UTC, k2madureira commented on src/services/users/update.service.js
> +    const findAdm = await userRepository.find({
middleware criado, porém não é aplicável no contexto de user, onde o próprio usuário pode realizar a atualização do perfil

2021-01-26 13:18 UTC, diegolssantos commented on src/routes/users.routes.js
> +router.put('/update/:id', validate(users.update), userController.update);
Exatamente, os métodos já fazem essa diferença nos padrões.
router.post('/'): cadastrar
router.put('/'): editar

2021-01-26 13:21 UTC, diegolssantos commented on src/services/users/session.service.js
> +    if (userData.disabled === true) {
Realmente, não considerei as duas validações distintas, desconsidere o meu comentário :+1:

2021-01-26 13:59 UTC, k2madureira commented on src/routes/users.routes.js
> +router.put('/update/:id', validate(users.update), userController.update);
Aplicado

2021-01-26 14:29 UTC, diegolssantos approved these changes

2021-01-26 14:33 UTC, merged

2021-01-26 15:03 UTC, diogo26 requested changes

2021-01-26 15:03 UTC, diogo26 commented on src/routes/users.routes.js
> +router.put('/:id', validate(users.update), userController.update);
So uma sugestão, cria uma rota com o patch para o update também.

2021-01-26 15:03 UTC, diogo26 commented on src/services/users/create.service.js
>      const findUser = await userRepository.find({ email });
Aqui você pode usar o `findOne` que você criou e no if da linha de baixo verificar a variável findUser no lugar de verificar o length.

2021-01-26 15:03 UTC, diogo26 commented on src/services/users/session.service.js
> +    if (findUser.length <= 0) {
Array não tem length negativo, deixe a validação para igual a zero ou utilize o `findOne`

2021-01-26 15:03 UTC, diogo26 commented on src/services/users/update.service.js
> +        messages.notFound('fields (password / passwordConfirmation)'),
Aqui você não deveria usar o `notFoundFields` que você criou? Por isso um `notFound` genérico ficaria melhor

2021-01-26 15:03 UTC, diogo26 commented on src/services/users/update.service.js
> +    const findAdm = await userRepository.find({
Não seria mais fácil na hora de gerar o token da sessão do `current_user` colocar se ele é admin ou não? Porque ai você faria a validação por ele. Na hora de decodificar a token do usuário adiciona o objeto do usuário na request e valida por ele.

2021-01-26 15:03 UTC, diogo26 commented on src/helpers/messages.js
> +  notFoundFields: arr => `${arr.toString()} not-found`,
Não seria melhor fazer um `notFound` genérico? Dois pode ficar confuso la na frente

2021-01-26 16:29 UTC, k2madureira commented on src/services/users/session.service.js
> +    if (findUser.length <= 0) {
Aplicado

2021-01-26 16:39 UTC, k2madureira commented on src/services/users/update.service.js
> +        messages.notFound('fields (password / passwordConfirmation)'),
Aplicado

2021-01-26 17:08 UTC, k2madureira commented on src/helpers/messages.js
> +  notFoundFields: arr => `${arr.toString()} not-found`,
Aplicado